language: python
os:
  - linux
matrix:
  fast_finish: true
  include:
    - python: 2.7
      env: TOXENV=py27-aws
    - python: 3.5
      env: TOXENV=py35-aws
    - python: pypy
      env: TOXENV=pypy-aws
    - python: 2.7
      env: TOXENV=py27-openstack
    - python: 3.5
      env: TOXENV=py35-openstack
    - python: pypy
      env: TOXENV=pypy-openstack
install:
  - pip install tox
  - pip install coveralls
script:
  - tox -e $TOXENV
after_success:
  - coveralls
